name: Go Status Check
on: [pull_request]

jobs:
  gocheckuts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go get .
      - name: Build Test
        run: go build main.go
      - name: Unit Tests
        run: go test ./...
